### ISSUE TITLE
Análisis de Aplicación con Realidad Aumentada

### ISSUE THREAD

**Issue by MaGuadalupeQuiroz** [SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-MaGuadalupeQuiroz#2]
[Analisis RA.pdf](https://github.com/SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-MaGuadalupeQuiroz/files/8081520/Analisis.RA.pdf)

**Comment by claudiasilvavenda** [comment]
El análisis de RA cumple con lo que pide la rubrica.
la calif. es 20%.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
